### PR TITLE
update model.py usage information

### PR DESCRIPTION
**Pull request by arwer13**
Part of new cli usage functionality moved to ref_to_high_level_classes branch by mistake, I suggest to continue it there...

### CODE REVIEW

**Comment by epogrebnyak** [comment]
@arwer13 : is it correct I deleted the branch `cli_change`?

**Comment by epogrebnyak** [comment]
[here](https://github.com/epogrebnyak/make-xls-model/blob/ref_to_high_level_classes/make_xls_model/model.py#L69-L85): 
- [ ] need comment: why use `_` as a variable name? is it some convention for dummy class instance?
- [ ] I removed 'sheet' from `-D` in 6af118c4fd87fcb06f0997bd10ddb38331621116 as it is not used
- [ ] default behaviour for `model.py <xlfile>` should be update, not create model, please adjust

**Comment by arwer13** [comment]
Yep, ok.
15.03.2016 11:40 пользователь "Evgeny Pogrebnyak" notifications@github.com
написал:

**Comment by arwer13** [comment]
- I don't know any conventions about it,  thought it might be clearer than
  some dummy name.
- Ok, I'll adjust it
  15.03.2016 11:52 пользователь "Evgeny Pogrebnyak" notifications@github.com
  написал:

**Pull request merged**
